mtasc -swf lib/classes.swf -header 1:1:24 src/Logger.as src/Utils.as src/GameMove.as src/GameInfo.as src/GameRecord.as \
src/games_GoSeigen/G1.as \
src/games_GoSeigen/G2.as \
src/games_GoSeigen/G3.as \
src/games_GoSeigen/G4.as \
src/games_GoSeigen/G5.as \
src/games_GoSeigen/G6.as \
src/games_GoSeigen/G7.as \
src/games_GoSeigen/G8.as \
src/games_GoSeigen/G9.as \
src/games_GoSeigen/G10.as \
src/games_GoSeigen/G11.as \
src/games_GoSeigen/G12.as \
src/games_GoSeigen/G13.as \
src/games_GoSeigen/G14.as \
src/games_GoSeigen/G15.as \
src/games_GoSeigen/G16.as \
src/games_GoSeigen/G17.as \
src/games_GoSeigen/G18.as \
src/games_GoSeigen/G19.as \
src/games_GoSeigen/G20.as \
src/games_GoSeigen/G21.as \
src/games_GoSeigen/G22.as \
src/games_GoSeigen/G23.as \
src/games_GoSeigen/G24.as \
src/games_GoSeigen/G25.as \
src/games_GoSeigen/G26.as \
src/games_GoSeigen/G27.as \
src/games_GoSeigen/G28.as \
src/games_GoSeigen/G29.as \
src/games_GoSeigen/G30.as \
src/games_GoSeigen/G31.as \
src/games_GoSeigen/G32.as \
src/games_GoSeigen/G33.as \
src/games_GoSeigen/G34.as \
src/games_GoSeigen/G35.as \
src/games_GoSeigen/G36.as \
src/games_GoSeigen/G37.as \
src/games_GoSeigen/G38.as \
src/games_GoSeigen/G39.as \
src/games_GoSeigen/G40.as \
src/games_GoSeigen/G41.as \
src/games_GoSeigen/G42.as \
src/games_GoSeigen/G43.as \
src/games_GoSeigen/G44.as \
src/games_GoSeigen/G45.as \
src/games_GoSeigen/G46.as \
src/games_GoSeigen/G47.as \
src/games_GoSeigen/G48.as \
src/games_GoSeigen/G49.as \
src/games_GoSeigen/G50.as \
src/games_GoSeigen/G51.as \
src/games_GoSeigen/G52.as \
src/games_GoSeigen/G53.as \
src/games_GoSeigen/G54.as \
src/games_GoSeigen/G55.as \
src/games_GoSeigen/G56.as \
src/games_GoSeigen/G57.as \
src/games_GoSeigen/G58.as \
src/games_GoSeigen/G59.as \
src/games_GoSeigen/G60.as \
src/games_GoSeigen/G61.as \
src/games_GoSeigen/G62.as \
src/games_GoSeigen/G63.as \
src/games_GoSeigen/G64.as \
src/games_GoSeigen/G65.as \
src/games_GoSeigen/G66.as \
src/games_GoSeigen/G67.as \
src/games_GoSeigen/G68.as \
src/games_GoSeigen/G69.as \
src/games_GoSeigen/G70.as \
src/games_GoSeigen/G71.as \
src/games_GoSeigen/G72.as \
src/games_GoSeigen/G73.as \
src/games_GoSeigen/G74.as \
src/games_GoSeigen/G75.as \
src/games_GoSeigen/G76.as \
src/games_GoSeigen/G77.as \
src/games_GoSeigen/G78.as \
src/games_GoSeigen/G79.as \
src/games_GoSeigen/G80.as \
src/games_GoSeigen/G81.as \
src/games_GoSeigen/G82.as \
src/games_GoSeigen/G83.as \
src/games_GoSeigen/G84.as \
src/games_GoSeigen/G85.as \
src/games_GoSeigen/G86.as \
src/GameRecordCollection.as src/GameState.as src/GameDisplay.as src/Observer.as src/Application.as

swfmill simple src/app.xml build/chumgo_goseigen.swf
